window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    // ╔══════════════════════════════════════════════════════════════╗
    // ║  TEXTBOOK 1: "Odia Bhasa" (Holyfaith) — LANGUAGE & GRAMMAR ║
    // ╚══════════════════════════════════════════════════════════════╝
    { num: 501, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ବ୍ୟାକରଣ (Grammar & Vocabulary)", difficulty: "Easy", length: "Short", tags: ["COMPLETED", "10 QUESTIONS"], href: "subjects/odia/grammar.html", desc: "ପ୍ରତିଶବ୍ଦ, ବିପରୀତ ଶବ୍ଦ, ରୂଢି। (Synonyms, antonyms, idioms.)", modules: [{ name: "ପାଠ: ଶବ୍ଦଜ୍ଞାନ (Vocabulary)", type: "summary", href: "subjects/odia/grammar.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/grammar.html#slide-03" }] },
    { num: 502, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ସନ୍ଧି ଓ ସମାସ (Sandhi & Samasa)", difficulty: "Moderate", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/sandhi_samasa.html", desc: "ସ୍ୱର ସନ୍ଧି, ବ୍ୟଞ୍ଜନ ସନ୍ଧି, ବିସର୍ଗ ସନ୍ଧି ଓ ସମାସ। (Sandhi types & compound words.)", modules: [{ name: "ପାଠ: ସନ୍ଧି ଓ ସମାସ (Lesson)", type: "summary", href: "subjects/odia/sandhi_samasa.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/sandhi_samasa.html#slide-03" }] },
    { num: 503, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ପ୍ରବନ୍ଧ ରଚନା (Composition)", difficulty: "Moderate", length: "Lengthy", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/composition.html", desc: "ବର୍ଣ୍ଣନାତ୍ମକ, ବିବରଣାତ୍ମକ ଓ ଚିନ୍ତାମୂଳକ ପ୍ରବନ୍ଧ। (Essay writing techniques.)", modules: [{ name: "ପାଠ: ପ୍ରବନ୍ଧ ଶୈଳୀ (Lesson)", type: "summary", href: "subjects/odia/composition.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/composition.html#slide-03" }] },
    { num: 504, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ପତ୍ର ଲିଖନ (Letter Writing)", difficulty: "Easy", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/letter_writing.html", desc: "ସରକାରୀ ଓ ବ୍ୟକ୍ତିଗତ ପତ୍ର। (Formal & informal letters.)", modules: [{ name: "ପାଠ: ପତ୍ର ଶୈଳୀ (Lesson)", type: "summary", href: "subjects/odia/letter_writing.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/letter_writing.html#slide-03" }] },
    { num: 505, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ଅବୋଧ ପରୀକ୍ଷଣ (Comprehension)", difficulty: "Moderate", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/comprehension.html", desc: "ଅପଠିତ ଗଦ୍ୟାଂଶ ପଢି ପ୍ରଶ୍ନୋତ୍ତର। (Unseen passage comprehension.)", modules: [{ name: "ପାଠ: ବୋଧ ଜ୍ଞାନ (Lesson)", type: "summary", href: "subjects/odia/comprehension.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/comprehension.html#slide-03" }] },

    // ╔══════════════════════════════════════════════════════════════════╗
    // ║  TEXTBOOK 2: "Gyananjali" (Friends Publishers) — SHORT STORIES ║
    // ╚══════════════════════════════════════════════════════════════════╝
    { num: 511, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୧: ଧୂଳିଆ ବାବା (Dhulia Baba)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/dhulia_baba.html", desc: "ଫକୀର ମୋହନ ସେନାପତି — ଗ୍ରାମୀଣ ଓଡ଼ିଶା, ବିଶ୍ୱାସ ଓ ସଂସ୍କାର। (Fakir Mohan Senapati.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/dhulia_baba.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/dhulia_baba.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/dhulia_baba.html#slide-04" }] },
    { num: 512, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୨: ଭଦ୍ରଲୋକ (Bhadraloka)", difficulty: "Difficult", length: "Lengthy", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/bhadraloka.html", desc: "ପ୍ରତିଭା ରାୟ — ସାମାଜିକ ଭଣ୍ଡାମି ଓ ଶ୍ରେଣୀ ବିଭେଦ। (Prativa Ray.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/bhadraloka.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/bhadraloka.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/bhadraloka.html#slide-04" }] },
    { num: 513, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୩: ଶିକାର (Shikar)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/shikar.html", desc: "ଭଗବତୀ ଚରଣ ପାଣିଗ୍ରାହୀ — ଶିକାର, ମଣିଷ ବନାମ ପ୍ରକୃତି। (Bhagabati Charan Panigrahi.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/shikar.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/shikar.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/shikar.html#slide-04" }] },
    { num: 514, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୪: କୃପଣ (Krupan)", difficulty: "Easy", length: "Short", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/krupan.html", desc: "ମନୋଜ ଦାସ — କୃପଣତା ଓ ଲୋଭର ପରିଣାମ। (Manoj Das.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/krupan.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/krupan.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/krupan.html#slide-04" }] },
    { num: 515, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୫: ମୁଖାଗ୍ନି (Mukhagni)", difficulty: "Difficult", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/mukhagni.html", desc: "ଲକ୍ଷ୍ମୀ ଚାନ୍ଦ — ମୃତ୍ୟୁ ସଂସ୍କାର, ପରିବାର ଓ ଶୋକ। (Laxmi Chand.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/mukhagni.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/mukhagni.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/mukhagni.html#slide-04" }] },
    { num: 516, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୬: ଡିମିରି ଫուଲ (Dimiri Phula)", difficulty: "Moderate", length: "Short", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/dimiri_phula.html", desc: "ଅଖିଳ ମୋହନ ପଟ୍ଟନାୟକ — ସରଳତା ଓ ଗ୍ରାମ୍ୟ ସୌନ୍ଦର୍ଯ୍ୟ। (Akhila Mohan Pattnayak.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/dimiri_phula.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/dimiri_phula.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/dimiri_phula.html#slide-04" }] },
    { num: 517, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୭: ସମାନ୍ତର ସରଳରେଖା (Samantara Saralarekha)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/samantara_saralarekha.html", desc: "ବିଭୂତି ପଟ୍ଟନାୟକ — ସାମାଜିକ ଅସମାନତା। (Bibhuti Pattanaik.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/samantara_saralarekha.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/samantara_saralarekha.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/samantara_saralarekha.html#slide-04" }] },
    { num: 518, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୮: ଅଙ୍ଗୁଠି (Anguthi)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/anguthi.html", desc: "ସଚ୍ଚିଦାନନ୍ଦ ରାଉତରାୟ — ବିଶ୍ୱାସ, ପ୍ରେମ ଓ ହାରାଇବା। (Sachidananda Routray.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/anguthi.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/anguthi.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/anguthi.html#slide-04" }] },

    // ╔══════════════════════════════════════════════════════════════╗
    // ║  TEXTBOOK 2: "Gyananjali" (Friends Publishers) — POETRY     ║
    // ╚══════════════════════════════════════════════════════════════╝
    { num: 521, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୧: ଗାନ୍ଧାରୀର ଆଶୀର୍ବାଦ (Gandharira Ashirwad)", difficulty: "Difficult", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/gandharira_ashirwad.html", desc: "କାଳିନ୍ଦୀ ଚରଣ ପାଣିଗ୍ରାହୀ — ମହାଭାରତ, ନ୍ୟାୟ ଓ ପ୍ରତିଶୋଧ। (Kalindi Charan Panigrahi.)", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/gandharira_ashirwad.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/gandharira_ashirwad.html#slide-03" }] },
    { num: 522, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୨: କାଳୀଜାଇ (Kalijai)", difficulty: "Moderate", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/kalijai.html", desc: "ଗୋଦାବରୀଶ ମିଶ୍ର — ଚିଳିକା ହ୍ରଦର ଲୋକକଥା। (Godabarish Mishra.)", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/kalijai.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/kalijai.html#slide-03" }] },
    { num: 523, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୩: ମହିମା (Mahima)", difficulty: "Moderate", length: "Short", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/mahima.html", desc: "ଗଙ୍ଗାଧର ମେହେର — ମହାନତା ଓ ନମ୍ରତା। (Gangadhar Meher.)", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/mahima.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/mahima.html#slide-03" }] },
    { num: 524, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୪: ବନଫୁଲ ଉଦ୍ୟାନ କୁସୁମ (Banaphula Udyana Kusuma)", difficulty: "Easy", length: "Short", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/banaphula.html", desc: "କୁନ୍ତଳା କୁମାରୀ ସାବତ — ପ୍ରାକୃତିକ ସୌନ୍ଦର୍ଯ୍ୟ। (Kuntala Kumari Sabat.)", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/banaphula.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/banaphula.html#slide-03" }] },

    // ╔══════════════════════════════════════════════════════════════╗
    // ║  BONUS: Previously built chapters (Rebati, Poetry, Drama)   ║
    // ╚══════════════════════════════════════════════════════════════╝
    { num: 531, subject: "odia", name: "ଅତିରିକ୍ତ: ରେବତୀ (Extra: Rebati)", difficulty: "Moderate", length: "Normal", tags: ["COMPLETED", "8 QUESTIONS"], href: "subjects/odia/rebati.html", desc: "ଫକୀର ମୋହନ ସେନାପତିଙ୍କ 'ରେବତୀ'। (Classic Odia short story.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/rebati.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/rebati.html#slide-03" }, { name: "ପରୀକ୍ଷା (Test)", type: "test", href: "subjects/odia/rebati.html#slide-04" }] },
    { num: 532, subject: "odia", name: "ଅତିରିକ୍ତ: ବନ୍ଦେ ଉତ୍କଳ ଜନନୀ (Extra: State Anthem)", difficulty: "Easy", length: "Short", tags: ["COMPLETED", "8 QUESTIONS"], href: "subjects/odia/poetry.html", desc: "ଓଡ଼ିଶାର ରାଜ୍ୟ ସଙ୍기ତ।", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/poetry.html#slide-02" }, { name: "ପରୀକ୍ଷା (Test)", type: "test", href: "subjects/odia/poetry.html#slide-03" }] },
    { num: 533, subject: "odia", name: "ଅତିରିକ୍ତ: ନାଟକ (Extra: Drama Analysis)", difficulty: "Moderate", length: "Short", tags: ["COMPLETED", "8 QUESTIONS"], href: "subjects/odia/drama.html", desc: "ନାଟକର ଚରିତ୍ର ଚିତ୍ରଣ।", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/drama.html#slide-02" }, { name: "ପରୀକ୍ଷା (Test)", type: "test", href: "subjects/odia/drama.html#slide-03" }] }
);
