window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    // ╔══════════════════════════════════════════════════════════════╗
    // ║  TEXTBOOK 1: "Odia Bhasa" (Holyfaith) — LANGUAGE & GRAMMAR ║
    // ╚══════════════════════════════════════════════════════════════╝
    { num: 1, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ବ୍ୟାକରଣ (Grammar & Vocabulary)", difficulty: "Easy", length: "Short", tags: ["COMPLETED", "10 QUESTIONS"], href: "subjects/odia/grammar.html", desc: "ପ୍ରତିଶବ୍ଦ, ବିପରୀତ ଶବ୍ଦ, ରୂଢି। (Synonyms, antonyms, idioms.)", modules: [{ name: "ପାଠ: ଶବ୍ଦଜ୍ଞାନ (Vocabulary)", type: "summary", href: "subjects/odia/grammar.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/grammar.html#slide-03" }] },
    { num: 2, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ସନ୍ଧି ଓ ସମାସ (Sandhi & Samasa)", difficulty: "Moderate", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/sandhi_samasa.html", desc: "ସ୍ୱର ସନ୍ଧି, ବ୍ୟଞ୍ଜନ ସନ୍ଧି, ବିସର୍ଗ ସନ୍ଧି ଓ ସମାସ। (Sandhi types & compound words.)", modules: [{ name: "ପାଠ: ସନ୍ଧି ଓ ସମାସ (Lesson)", type: "summary", href: "subjects/odia/sandhi_samasa.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/sandhi_samasa.html#slide-03" }] },
    { num: 3, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ପ୍ରବନ୍ଧ ରଚନା (Composition)", difficulty: "Moderate", length: "Lengthy", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/composition.html", desc: "ବର୍ଣ୍ଣନାତ୍ମକ, ବିବରଣାତ୍ମକ ଓ ଚିନ୍ତାମୂଳକ ପ୍ରବନ୍ଧ। (Essay writing techniques.)", modules: [{ name: "ପାଠ: ପ୍ରବନ୍ଧ ଶୈଳୀ (Lesson)", type: "summary", href: "subjects/odia/composition.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/composition.html#slide-03" }] },
    { num: 4, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ପତ୍ର ଲିଖନ (Letter Writing)", difficulty: "Easy", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/letter_writing.html", desc: "ସରକାରୀ ଓ ବ୍ୟକ୍ତିଗତ ପତ୍ର। (Formal & informal letters.)", modules: [{ name: "ପାଠ: ପତ୍ର ଶୈଳୀ (Lesson)", type: "summary", href: "subjects/odia/letter_writing.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/letter_writing.html#slide-03" }] },
    { num: 5, subject: "odia", name: "ଓଡ଼ିଆ ଭାଷା — ଅବୋଧ ପରୀକ୍ଷଣ (Comprehension)", difficulty: "Moderate", length: "Normal", tags: ["4 SLIDES", "8 QUESTIONS"], href: "subjects/odia/comprehension.html", desc: "ଅପଠିତ ଗଦ୍ୟାଂଶ ପଢି ପ୍ରଶ୍ନୋତ୍ତର। (Unseen passage comprehension.)", modules: [{ name: "ପାଠ: ବୋଧ ଜ୍ଞାନ (Lesson)", type: "summary", href: "subjects/odia/comprehension.html#slide-02" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/comprehension.html#slide-03" }] },

    // ╔══════════════════════════════════════════════════════════════════╗
    // ║  TEXTBOOK 2: "Gyananjali" (Friends Publishers) — SHORT STORIES ║
    // ╚══════════════════════════════════════════════════════════════════╝
    { num: 6, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୧: ଧୂଳିଆ ବାବା (Dhulia Baba)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/dhulia_baba.html", desc: "ଫକୀର ମୋହନ ସେନାପତି — ଗ୍ରାମୀଣ ଓଡ଼ିଶା, ବିଶ୍ୱାସ ଓ ସଂସ୍କାର। (Fakir Mohan Senapati.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/dhulia_baba.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/dhulia_baba.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/dhulia_baba.html#slide-04" }] },
    { num: 7, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୨: ଭଦ୍ରଲୋକ (Bhadraloka)", difficulty: "Difficult", length: "Lengthy", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/bhadraloka.html", desc: "ପ୍ରତିଭା ରାୟ — ସାମାଜିକ ଭଣ୍ଡାମି ଓ ଶ୍ରେଣୀ ବିଭେଦ। (Prativa Ray.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/bhadraloka.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/bhadraloka.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/bhadraloka.html#slide-04" }] },
    { num: 8, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୩: ଶିକାର (Shikar)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/shikar.html", desc: "ଭଗବତୀ ଚରଣ ପାଣିଗ୍ରାହୀ — ଶିକାର, ମଣିଷ ବନାମ ପ୍ରକୃତି। (Bhagabati Charan Panigrahi.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/shikar.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/shikar.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/shikar.html#slide-04" }] },
    { num: 9, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୪: କୃପଣ (Krupan)", difficulty: "Easy", length: "Short", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/krupan.html", desc: "ମନୋଜ ଦାସ — କୃପଣତା ଓ ଲୋଭର ପରିଣାମ। (Manoj Das.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/krupan.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/krupan.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/krupan.html#slide-04" }] },
    { num: 10, subject: "odia", name: "ଗ୍ୟାନาଞ୍ଜଳି ଗଳ୍ପ ୫: ମୁଖାଗ୍ନି (Mukhagni)", difficulty: "Difficult", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/mukhagni.html", desc: "ଲକ୍ଷ୍ମୀ ଚାନ୍ଦ — ମୃତյୁ ସଂସ୍କାର, ପରିବାର ଓ ଶୋକ। (Laxmi Chand.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/mukhagni.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/mukhagni.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/mukhagni.html#slide-04" }] },
    { num: 11, subject: "odia", name: "ଗ୍ୟାନาଞ୍ଜଳି ଗଳ୍ପ ୬: ଡିମିରି ଫուଲ (Dimiri Phula)", difficulty: "Moderate", length: "Short", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/dimiri_phula.html", desc: "ଅଖିଳ ମୋହନ ପଟ୍ଟନାୟକ — ସରଳତା ଓ ଗ୍ରାମ୍ୟ ସୌନ୍ଦର୍ଯ୍ୟ। (Akhila Mohan Pattnayak.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/dimiri_phula.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/dimiri_phula.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/dimiri_phula.html#slide-04" }] },
    { num: 12, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୭: ସମାନ୍ତର ସରଳରେଖା (Samantara Saralarekha)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/samantara_saralarekha.html", desc: "ବିଭୂତି ପଟ୍ଟନାୟକ — ସାମାଜିକ ଅସମାନତା। (Bibhuti Pattanaik.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/samantara_saralarekha.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/samantara_saralarekha.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/samantara_saralarekha.html#slide-04" }] },
    { num: 13, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି ଗଳ୍ପ ୮: ଅଙ୍ଗୁଠି (Anguthi)", difficulty: "Moderate", length: "Normal", tags: ["5 SLIDES", "8 QUESTIONS"], href: "subjects/odia/anguthi.html", desc: "ସଚ୍ଚିଦାନନ୍ଦ ରାଉତରାୟ — ବିଶ୍ୱାସ, ପ୍ରେମ ଓ ହାରାଇବା। (Sachidananda Routray.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/anguthi.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/anguthi.html#slide-03" }, { name: "ପରୀକ୍ଷା (Quiz)", type: "test", href: "subjects/odia/anguthi.html#slide-04" }] },

    // ╔══════════════════════════════════════════════════════════════╗
    // ║  TEXTBOOK 2: "Gyananjali" (Friends Publishers) — POETRY     ║
    // ╚══════════════════════════════════════════════════════════════╝
    { num: 14, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୧: ଜଗତେ କେବଳ (Jagate Kebala)", difficulty: "Difficult", length: "Normal", tags: ["COMING SOON"], href: "#", desc: "କବିସୂର୍ଯ୍ୟ ବଳଦେବ ରଥ — ମାନବ ଜୀବନର କ୍ଷଣଭଙ୍ଗୁରତା ଓ ସଂସାରର ଅନିତ୍ୟତା। (Kabisurya Baladev Ratha.)" },
    { num: 15, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୨: ଗ୍ରାମପଥ (Grampatha)", difficulty: "Easy", length: "Short", tags: ["COMING SOON"], href: "#", desc: "ବିନୋଦ ଚନ୍ଦ୍ର ନାୟକ — ଗ୍ରାମ୍ୟ ଜୀବନର ସୌନ୍ଦର୍ଯ୍ୟ ଓ ପ୍ରକୃତିର ନିଚ୍ଛକ ସମ୍ପର୍କ। (Binod Chandra Nayak.)" },
    { num: 16, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୩: ମଣି କାଞ୍ଚନ ଯୋଗ (Mani Kanchan Joga)", difficulty: "Moderate", length: "Normal", tags: ["COMING SOON"], href: "#", desc: "ରାଧାମୋହନ ଗଡ଼ନାୟକ — ଦୁଇଟି ମହାନ ଉପାଦାନର ସମ୍ମିଳନୀ, ସମ୍ପର୍କର ପରାକାଷ୍ଠା। (Radhamohan Gadanaik.)" },
    { num: 17, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୪: ବନ୍ଦୀର ବିରହ ବ୍ୟଥା (Bandira Biraha Byatha)", difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "ଉତ୍କଳମଣି ଗୋପବନ୍ଧୁ ଦାସ — ମାତୃଭୂମିର ସେବା ଓ କାରାଗାର ମଧ୍ୟରେ ଥିବା ଏକ ବନ୍ଦୀର ବିରହ ବ୍ୟଥା। (Utkalmani Gopabandhu Das.)" },
    { num: 18, subject: "odia", name: "ଗ୍ୟାନାଞ୍ଜଳି କବିତା ୫: ଖଦ୍ୟୋତିକା (Khadyotika)", difficulty: "Moderate", length: "Short", tags: ["COMING SOON"], href: "#", desc: "ବିଦ୍ୟୁତପ୍ରଭା ଦେବୀ — ଜୀବନ ଓ ପ୍ରକୃତିର ଏକ ଅନନ୍ୟ ଉପଲବ୍ଧି, ସୂକ୍ଷ୍ମ ଅନୁଭୂତି। (Bidyutprava Devi.)" },

    // ╔══════════════════════════════════════════════════════════════╗
    // ║  BONUS: Previously built chapters (Rebati, Poetry, Drama)   ║
    // ╚══════════════════════════════════════════════════════════════╝
    { num: 19, subject: "odia", name: "ଅତିରିକ୍ତ: ରେବତୀ (Extra: Rebati)", difficulty: "Moderate", length: "Normal", tags: ["COMPLETED", "8 QUESTIONS"], href: "subjects/odia/rebati.html", desc: "ଫକୀର ମୋହନ ସେନାପତିଙ୍କ 'ରେବତୀ'। (Classic Odia short story.)", modules: [{ name: "ଭାଗ ୧ (Part 1)", type: "summary", href: "subjects/odia/rebati.html#slide-02" }, { name: "ଭାଗ ୨ (Part 2)", type: "summary", href: "subjects/odia/rebati.html#slide-03" }, { name: "ପରୀକ୍ଷା (Test)", type: "test", href: "subjects/odia/rebati.html#slide-04" }] },
    { num: 20, subject: "odia", name: "ଅତିରିକ୍ତ: ବନ୍ଦେ ଉତ୍କଳ ଜନନୀ (Extra: State Anthem)", difficulty: "Easy", length: "Short", tags: ["COMPLETED", "8 QUESTIONS"], href: "subjects/odia/poetry.html", desc: "ଓଡ଼ିଶାର ରାଜ୍ୟ ସଙ୍ଗୀତ।", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/poetry.html#slide-02" }, { name: "ପରୀକ୍ଷା (Test)", type: "test", href: "subjects/odia/poetry.html#slide-03" }] },
    { num: 21, subject: "odia", name: "ଅତିରିକ୍ତ: ନାଟକ (Extra: Drama Analysis)", difficulty: "Moderate", length: "Short", tags: ["COMPLETED", "8 QUESTIONS"], href: "subjects/odia/drama.html", desc: "ନାଟକର ଚରିତ୍ର ଚିତ୍ରଣ।", modules: [{ name: "ପାଠ (Lesson)", type: "summary", href: "subjects/odia/drama.html#slide-02" }, { name: "ପରୀକ୍ଷା (Test)", type: "test", href: "subjects/odia/drama.html#slide-03" }] }
);
