window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 1, subject: "economics", name: "Elementary Theory of Demand",          difficulty: "Easy",      length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Meaning of demand, demand schedule, demand curve, Law of Demand, determinants, and movements vs shifts along the curve." },
    { num: 2, subject: "economics", name: "Elasticity of Demand",                  difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Meaning, price elasticity of demand, degrees of elasticity, measurement methods, and factors affecting elasticity." },
    { num: 3, subject: "economics", name: "Theory of Supply",                      difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Meaning of supply, Law of Supply, supply curve, determinants of supply, and movements vs shifts along the supply curve." },
    { num: 4, subject: "economics", name: "Factors of Production",                 difficulty: "Moderate",  length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Land (features), Labour (efficiency), Capital (types, capital formation), and Entrepreneur (role, qualities)." },
    { num: 5, subject: "economics", name: "Nature and Structure of Markets",        difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Definition of market, Perfect Competition, Monopoly, Monopolistic Competition, and Oligopoly (meaning & features)." },
    { num: 6, subject: "economics", name: "The State and Economic Development",    difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Role of the state, Public Revenue (Direct/Indirect Taxes), Public Expenditure, Public Debt, and Deficit Financing." },
    { num: 7, subject: "economics", name: "Meaning and Functions of Money",         difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Barter system limitations, evolution of money, primary, secondary, and contingent functions of money." },
    { num: 8, subject: "economics", name: "Commercial Banks",                      difficulty: "Easy",      length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Meaning, primary functions (deposits, loans), credit creation, agency functions, and general utility services." },
    { num: 9, subject: "economics", name: "Central Banks",                         difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Functions of RBI: Bank of issue, banker to the govt, controller of credit (CRR, SLR, Repo, Bank Rate, open market ops)." },
    { num: 10, subject: "economics", name: "Inflation",                             difficulty: "Moderate",  length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Definition, types (creeping, walking, running, galloping), Demand-Pull vs Cost-Push causes, and effects." }
);
