window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 1, subject: "math",       name: "GST (Goods & Services Tax)",        difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Computation of tax, discount, list price, profit/loss with GST, and input/output tax credit calculations." },
    { num: 2, subject: "math",       name: "Banking — Recurring Deposits",      difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Maturity value, interest computation using formula, and inverse problems on recurring deposit accounts." },
    { num: 3, subject: "math",       name: "Shares & Dividends",                difficulty: "Moderate",  length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Face value vs market value, dividend calculation, rate of return, and investment-based word problems." },
    { num: 4, subject: "math",       name: "Linear Inequations",                difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Solving in one variable, number line representation, and solution sets using integers and real numbers." },
    { num: 5, subject: "math",       name: "Quadratic Equations",               difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Nature of roots (discriminant), solution by factorisation & formula, word problems on area, speed, and ages." },
    { num: 6, subject: "math",       name: "Ratio & Proportion",                difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Componendo-dividendo, alternendo-invertendo, and application of proportion properties in algebraic expressions." },
    { num: 7, subject: "math",       name: "Factor & Remainder Theorem",        difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Factorisation of polynomials using factor theorem, finding remainders, and determining unknown coefficients." },
    { num: 8, subject: "math",       name: "Matrices",                          difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Order, types (row, column, square, null, identity), addition, subtraction, scalar multiplication & matrix multiplication." },
    { num: 9, subject: "math",       name: "Arithmetic & Geometric Progressions", difficulty: "Moderate", length: "Normal", tags: ["COMING SOON"], href: "#", desc: "nth term, sum of n terms, common difference/ratio, finding unknowns, and real-world application problems." },
    { num: 10, subject: "math",       name: "Coordinate Geometry",               difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Reflection, section & mid-point formula, slope, equation of a line (slope-intercept, point-slope, two-point form)." },
    { num: 11, subject: "math",       name: "Similarity",                        difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "AA/SAS/SSS criteria, Basic Proportionality Theorem (BPT), areas of similar triangles, and proof-based questions." },
    { num: 12, subject: "math",       name: "Loci",                              difficulty: "Moderate",  length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Concept of locus, theorems on perpendicular bisectors, angle bisectors, and construction-based loci problems." },
    { num: 13, subject: "math",       name: "Circles",                           difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Angle properties, cyclic quadrilaterals, tangent properties, arc-chord relationships, and construction of tangents." },
    { num: 14, subject: "math",       name: "Mensuration",                       difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Surface area & volume of cylinders, cones, spheres, hemispheres, and composite solids. Conversion problems." },
    { num: 15, subject: "math",       name: "Trigonometry",                      difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Trigonometric identities, proving equations, heights & distances, angles of elevation/depression, and complementary angles." },
    { num: 16, subject: "math",       name: "Statistics",                        difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Mean (direct/step-deviation), median & mode for grouped data, histograms, frequency polygons, and ogive curves." },
    { num: 17, subject: "math",       name: "Probability",                       difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Random experiments, sample space, simple/compound events, dice & cards problems, and complementary probability." }
);
