window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 73, subject: "geography",  name: "Map Study — Topographical Maps",    difficulty: "Moderate",  length: "Normal",  tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/topo.html", desc: "Grid references, contour interpretation, conventional symbols, relief features, and 4/6-figure grid calculations.", modules: [{ name: "Lesson: Grids & Scales", type: "summary", href: "subjects/geography/topo.html#slide-02" }, { name: "Lesson: Contours & Interpretations", type: "summary", href: "subjects/geography/topo.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/topo.html#slide-06" }] },
    { num: 74, subject: "geography",  name: "Location, Extent & Physical Features", difficulty: "Easy",  length: "Normal",  tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/location.html", desc: "India's position, neighboring countries, major physiographic divisions — Himalayas, Northern Plains, Peninsular Plateau, Coastal Plains & Islands.", modules: [{ name: "Lesson: Location & Extent", type: "summary", href: "subjects/geography/location.html#slide-02" }, { name: "Lesson: Physical Divisions", type: "summary", href: "subjects/geography/location.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/location.html#slide-06" }] },
    { num: 75, subject: "geography",  name: "Climate of India",                  difficulty: "Moderate",  length: "Lengthy", tags: ["10 SLIDES", "50 QUESTIONS"], href: "subjects/geography/climate.html", desc: "Monsoon mechanism, factors affecting climate, seasons (summer, monsoon, retreating monsoon, winter), and regional variations.", modules: [{ name: "Lesson: Factors Affecting Climate", type: "summary", href: "subjects/geography/climate.html#slide-02" }, { name: "Lesson: The Four Seasons", type: "summary", href: "subjects/geography/climate.html#slide-03" }, { name: "Quiz: Climate Check", type: "test", href: "subjects/geography/climate.html#slide-04" }] },
    { num: 76, subject: "geography",  name: "Soil Resources",                    difficulty: "Easy",      length: "Short",   tags: ["8 SLIDES", "33 QUESTIONS"], href: "subjects/geography/soil.html", desc: "Soil formation, types (alluvial, black, red, laterite), soil profile, erosion types, and conservation methods.", modules: [{ name: "Lesson: Alluvial & Black Soil", type: "summary", href: "subjects/geography/soil.html#slide-02" }, { name: "Lesson: Red & Laterite Soil", type: "summary", href: "subjects/geography/soil.html#slide-04" }, { name: "Quiz: Soil Erosion", type: "test", href: "subjects/geography/soil.html#slide-06" }] },
    { num: 77, subject: "geography",  name: "Natural Vegetation",                difficulty: "Easy",      length: "Normal",  tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/vegetation.html", desc: "Types: tropical evergreen, deciduous, desert, tidal, mountain. Importance of forests, deforestation, and conservation.", modules: [{ name: "Lesson: Tropical Forests", type: "summary", href: "subjects/geography/vegetation.html#slide-02" }, { name: "Lesson: Other Forests", type: "summary", href: "subjects/geography/vegetation.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/vegetation.html#slide-06" }] },
    { num: 78, subject: "geography",  name: "Water Resources",                   difficulty: "Easy",      length: "Short",   tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/water.html", desc: "Surface & groundwater sources, irrigation methods (wells, canals, tanks), water conservation, and rainwater harvesting.", modules: [{ name: "Lesson: Irrigation Types", type: "summary", href: "subjects/geography/water.html#slide-02" }, { name: "Lesson: Rainwater Harvesting", type: "summary", href: "subjects/geography/water.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/water.html#slide-06" }] },
    { num: 79, subject: "geography",  name: "Mineral & Energy Resources",        difficulty: "Moderate",  length: "Normal",  tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/minerals.html", desc: "Distribution of iron ore, manganese, coal, petroleum. Conventional & non-conventional energy sources and conservation.", modules: [{ name: "Lesson: Metallic Minerals", type: "summary", href: "subjects/geography/minerals.html#slide-02" }, { name: "Lesson: Energy Resources", type: "summary", href: "subjects/geography/minerals.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/minerals.html#slide-06" }] },
    { num: 80, subject: "geography",  name: "Agriculture",                       difficulty: "Moderate",  length: "Lengthy", tags: ["7 SLIDES", "45 QUESTIONS"], href: "subjects/geography/agriculture.html", desc: "Farming types, Rabi/Kharif/Zaid seasons. Major crops: rice, wheat, sugarcane, cotton, jute, tea, coffee — conditions & distribution.", modules: [{ name: "Lesson: Farming & Seasons", type: "summary", href: "subjects/geography/agriculture.html#slide-02" }, { name: "Lesson: Major Crops", type: "summary", href: "subjects/geography/agriculture.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/agriculture.html#slide-06" }] },
    { num: 81, subject: "geography",  name: "Manufacturing Industries",          difficulty: "Moderate",  length: "Normal",  tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/manufacturing.html", desc: "Agro-based (cotton, jute, sugar) and mineral-based (iron & steel, cement) industries — location factors & distribution.", modules: [{ name: "Lesson: Agro-based Industries", type: "summary", href: "subjects/geography/manufacturing.html#slide-02" }, { name: "Lesson: Mineral-based & IT", type: "summary", href: "subjects/geography/manufacturing.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/manufacturing.html#slide-06" }] },
    { num: 82, subject: "geography",  name: "Transport",                         difficulty: "Easy",      length: "Short",   tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/transport.html", desc: "Road, rail, waterway & airway networks. Golden Quadrilateral, major ports, and the role of transport in economic development.", modules: [{ name: "Lesson: Land Transport", type: "summary", href: "subjects/geography/transport.html#slide-02" }, { name: "Lesson: Water & Air Transport", type: "summary", href: "subjects/geography/transport.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/transport.html#slide-06" }] },
    { num: 83, subject: "geography",  name: "Waste Management",                  difficulty: "Easy",      length: "Short",   tags: ["7 SLIDES", "35 QUESTIONS"], href: "subjects/geography/waste.html", desc: "Types of waste, safe disposal methods, composting, recycling, biogas, and the need for waste management in India.", modules: [{ name: "Lesson: Types & Sources", type: "summary", href: "subjects/geography/waste.html#slide-02" }, { name: "Lesson: Disposal & 3 Rs", type: "summary", href: "subjects/geography/waste.html#slide-04" }, { name: "Mega Revision", type: "test", href: "subjects/geography/waste.html#slide-06" }] }
);
