window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 73, subject: "geography",  name: "Map Study — Topographical Maps",    difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Grid references, contour interpretation, conventional symbols, relief features, and 4/6-figure grid calculations." },
    { num: 74, subject: "geography",  name: "Location, Extent & Physical Features", difficulty: "Easy",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "India's position, neighboring countries, major physiographic divisions — Himalayas, Northern Plains, Peninsular Plateau, Coastal Plains & Islands." },
    { num: 75, subject: "geography",  name: "Climate of India",                  difficulty: "Moderate",  length: "Lengthy", tags: ["5 SLIDES", "4 QUESTIONS"], href: "subjects/geography/climate.html", desc: "Monsoon mechanism, factors affecting climate, seasons (summer, monsoon, retreating monsoon, winter), and regional variations." },
    { num: 76, subject: "geography",  name: "Soil Resources",                    difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Soil formation, types (alluvial, black, red, laterite), soil profile, erosion types, and conservation methods." },
    { num: 77, subject: "geography",  name: "Natural Vegetation",                difficulty: "Easy",      length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Types: tropical evergreen, deciduous, desert, tidal, mountain. Importance of forests, deforestation, and conservation." },
    { num: 78, subject: "geography",  name: "Water Resources",                   difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Surface & groundwater sources, irrigation methods (wells, canals, tanks), water conservation, and rainwater harvesting." },
    { num: 79, subject: "geography",  name: "Mineral & Energy Resources",        difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Distribution of iron ore, manganese, coal, petroleum. Conventional & non-conventional energy sources and conservation." },
    { num: 80, subject: "geography",  name: "Agriculture",                       difficulty: "Moderate",  length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Farming types, Rabi/Kharif/Zayad seasons. Major crops: rice, wheat, sugarcane, cotton, jute, tea, coffee — conditions & distribution." },
    { num: 81, subject: "geography",  name: "Manufacturing Industries",          difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Agro-based (cotton, jute, sugar) and mineral-based (iron & steel, cement) industries — location factors & distribution." },
    { num: 82, subject: "geography",  name: "Transport",                         difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Road, rail, waterway & airway networks. Golden Quadrilateral, major ports, and the role of transport in economic development." },
    { num: 83, subject: "geography",  name: "Waste Management",                  difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Types of waste, safe disposal methods, composting, recycling, biogas, and the need for waste management in India." }
);
