/* waste.js - Geography Chapter 83: Waste Management (Exhaustive Board Edition) */

// ============================================================
// COMPANION MESSAGES PER SLIDE
// ============================================================
window.CHAPTER_COMPANION_MESSAGES = [
    { face: "WELCOME", text: "Ready to become an environmental savior? Let's clean up our concepts! (ᵔ‿ᵔ)" },
    { face: "THINKING", text: "Biodegradable decomposes naturally; Non-biodegradable stays forever! (o_O)" },
    { face: "WELCOME", text: "Let's see how much you know about Waste Types, Sources, and their impacts." },
    { face: "HAPPY", text: "Composting enriches soil, while sanitary landfills protect our aquifers! (ᵔ‿ᵔ)" },
    { face: "WELCOME", text: "Time to test your knowledge on safe disposal methods and the 3 Rs." },
    { face: "THINKING", text: "Final eco challenge! Can you score 100% on the Waste Management test?" },
    { face: "GRADUATION", text: "Incredible job, Kinjal! You are officially an Eco Champion! \\(^ヮ^)/" }
];

// ============================================================
// QUIZ QUESTIONS BY SECTION (35 Questions Total)
// ============================================================
window.CHAPTER_QUESTIONS = {

    // ──────────────────────────────────────────────────────────
    // QUIZ 1: Types & Sources of Waste (12 Questions)
    // ──────────────────────────────────────────────────────────
    "q1": [
        {
            id: 'q1_1',
            sentence: 'Which of the following is classified as a "Biodegradable" waste?',
            options: ['Plastic Water Bottles', 'Kitchen vegetable peels', 'Aluminium drink cans', 'Glass jars'],
            correct: 1,
            rule: 'Classification',
            explanations: { correct: "Kitchen wastes are organic and can be decomposed by micro-organisms into simple compounds.", wrong: { 0: "Synthetic polymer, non-biodegradable.", 2: "Metal, non-biodegradable.", 3: "Silica-based, non-biodegradable." } }
        },
        {
            id: 'q1_2',
            sentence: 'What is a major characteristic of "Non-biodegradable" waste?',
            options: ['It decomposes in 2 days', 'It remains in the environment for years, causing long-term chemical and physical pollution', 'It turns into rich manure naturally', 'It is always liquid'],
            correct: 1,
            rule: 'Characteristics',
            explanations: { correct: "Non-biodegradable materials cannot be decomposed by biological processes, so they persist and accumulate in biosphere layers.", wrong: { 0: "Does not decompose.", 2: "That's biodegradable waste.", 3: "Can be solid, gas, or liquid." } }
        },
        {
            id: 'q1_3',
            sentence: 'Which of the following represents a primary source of "Industrial" waste?',
            options: ['Animal manure and crop husks', 'Fly ash from thermal power plants and chemical effluents', 'Kitchen sweepings and discarded furniture', 'Cardboard boxes and leaves'],
            correct: 1,
            rule: 'Sources',
            explanations: { correct: "Thermal power stations produce massive quantities of fly ash, and chemical industries release toxic liquid effluents.", wrong: { 0: "Agricultural waste.", 2: "Domestic waste.", 3: "Municipal/Domestic." } }
        },
        {
            id: 'q1_4',
            sentence: 'Why is open dumping of municipal waste considered highly hazardous to public health?',
            options: ['It attracts tourists', 'It acts as an ideal breeding ground for flies, mosquitoes, and rodents that spread diseases like plague and malaria', 'It makes the soil too fertile', 'It causes high snow precipitation'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "Uncovered garbage piles breed pathogens and vector pests, leading to epidemics in nearby residential tracts.", wrong: { 0: "Absurd option.", 2: "Open dumps destroy soil fertility.", 3: "No effect on snowfall." } }
        },
        {
            id: 'q1_5',
            sentence: 'Waste generated by shops, offices, hotels, and street sweepings in urban areas is classified under _____',
            options: ['Industrial Waste', 'Municipal Waste', 'Agricultural Waste', 'Radioactive Waste'],
            correct: 1,
            rule: 'Classification',
            explanations: { correct: "Municipal solid waste (MSW) comprises everyday items discarded by commercial and public establishments in municipal limits.", wrong: { 0: "From factories.", 2: "From farms.", 3: "From nuclear plants." } }
        },
        {
            id: 'q1_6',
            sentence: 'Which of the following is a dangerous chemical pesticide that is non-biodegradable and accumulates in the food chain?',
            options: ['Compost', 'Urea', 'DDT (Dichlorodiphenyltrichloroethane)', 'Cow dung'],
            correct: 2,
            rule: 'Chemical Waste',
            explanations: { correct: "DDT is a persistent organic pollutant that undergoes biomagnification, harming predators at the top of the food chain.", wrong: { 0: "Organic manure.", 1: "Soluble fertilizer.", 3: "Organic manure." } }
        },
        {
            id: 'q1_7',
            sentence: 'What is the environmental hazard known as "Eutrophication" caused by agricultural runoff?',
            options: ['Soil turning into sand', 'Excessive nutrient accumulation in water bodies leading to algal blooms and oxygen depletion, suffocating fish', 'Water becoming completely acidic', 'Earthquakes under lakes'],
            correct: 1,
            rule: 'Environmental Impact',
            explanations: { correct: "Fertilizers and organic waste washed into lakes trigger massive weed growth. As they die and rot, they consume all dissolved oxygen.", wrong: { 0: "Desertification.", 2: "Acidification is separate.", 3: "Tectonic." } }
        },
        {
            id: 'q1_8',
            sentence: 'Which type of waste includes old computers, broken smartphones, and electronic components?',
            options: ['Domestic organic waste', 'E-waste (Electronic waste)', 'Mining waste', 'Biodegradable municipal waste'],
            correct: 1,
            rule: 'Terminology',
            explanations: { correct: "E-waste contains hazardous metals like lead, mercury, and cadmium, requiring special recycling processes.", wrong: { 0: "Kitchen scraps.", 2: "Slag/tailings.", 3: "Paper/cardboard." } }
        },
        {
            id: 'q1_9',
            sentence: 'Why are organic wastes like crop residues and weeds considered agricultural waste?',
            options: ['Because they are produced on farms during cultivation and animal rearing', 'Because they are sold in grocery stores', 'Because they are made of plastic', 'Because they are toxic to crops'],
            correct: 0,
            rule: 'Sources',
            explanations: { correct: "Farm operations generate vast plant debris, husks, straw, and animal dung which are categorized as agro-waste.", wrong: { 1: "Food products are sold.", 2: "They are organic.", 3: "They are natural and decompose." } }
        },
        {
            id: 'q1_10',
            sentence: 'What is a major source of toxic heavy metal pollution (like mercury and lead) in aquatic environments?',
            options: ['Dairy farm runoff', 'Untreated industrial effluents discharged from battery, paint, and chemical factories', 'Forest leaf litter', 'Municipal paper recycling plants'],
            correct: 1,
            rule: 'Sources',
            explanations: { correct: "Heavy industrial units often discharge raw chemical effluents directly into rivers, contaminating the aquatic food chain.", wrong: { 0: "Contains organic nutrients.", 2: "Completely natural.", 3: "Generally cleaner process." } }
        },
        {
            id: 'q1_11',
            sentence: 'Non-biodegradable packaging materials like Styrofoam and bubble wrap are major contributors to _____',
            options: ['Aquifer recharging', 'Landfill overloading and visual clutter', 'Soil organic enrichment', 'Air moisture increase'],
            correct: 1,
            rule: 'Environmental Impact',
            explanations: { correct: "Lightweight synthetic packaging does not rot, leading to rapidly filling landfills and widespread littering.", wrong: { 0: "Blocks seepage.", 2: "Ruins soil.", 3: "No effect on humidity." } }
        },
        {
            id: 'q1_12',
            sentence: 'Why is the accumulation of e-waste highly hazardous?',
            options: ['It causes no problems', 'It contains highly toxic heavy metals like lead, cadmium, and mercury that can seep into soil and groundwater', 'It smells like rotten food', 'It causes immediate volcanic eruptions'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "When discarded in open landfills, the toxic metals inside circuit boards and batteries rust and dissolve into groundwater systems.", wrong: { 0: "Highly dangerous.", 2: "It doesn't rot like organic waste.", 3: "Absurd option." } }
        }
    ],

    // ──────────────────────────────────────────────────────────
    // QUIZ 2: Safe Disposal Methods & The 3 Rs (12 Questions)
    // ──────────────────────────────────────────────────────────
    "q2": [
        {
            id: 'q2_1',
            sentence: 'What is the absolute first step in modern scientific waste management?',
            options: ['Incineration', 'Waste Segregation (separating wet and dry wastes at source)', 'Deep-sea dumping', 'Open burning'],
            correct: 1,
            rule: 'Methods',
            explanations: { correct: "Segregation ensures that recyclables are sorted out, and organic waste remains pure for clean composting.", wrong: { 0: "Final disposal method.", 2: "Highly hazardous.", 3: "Causes extreme air pollution." } }
        },
        {
            id: 'q2_2',
            sentence: 'Which safe disposal method involves the aerobic decomposition of organic waste into rich humus using earthworms?',
            options: ['Vermicomposting', 'Sanitary Landfill', 'Incineration', 'Pyrolysis'],
            correct: 0,
            rule: 'Composting',
            explanations: { correct: "Vermicomposting utilizes earthworms (e.g., Red Wigglers) to break down organic matter quickly, enriching it with nutrients.", wrong: { 1: "Dumping method.", 2: "Burning method.", 3: "Thermal cracking without oxygen." } }
        },
        {
            id: 'q2_3',
            sentence: 'Why are sanitary landfills lined with heavy plastic sheets and thick clay layers?',
            options: ['To make the landfill look clean', 'To prevent highly toxic fluid residue (leachate) from seeping down and polluting groundwater aquifers', 'To catch rats', 'To keep the waste warm'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "Rainwater percolating through landfill waste forms 'leachate', a toxic cocktail that can ruin entire underground water tables if not contained.", wrong: { 0: "It is covered with soil, not visible.", 2: "Does not catch pests.", 3: "Temperature control is not the reason." } }
        },
        {
            id: 'q2_4',
            sentence: 'Which method is highly recommended for disposing of infectious and hazardous hospital waste (syringes, surgical dressings)?',
            options: ['Composting', 'Incineration (high-temperature thermal burning)', 'Recycling into toys', 'Open dumping on roads'],
            correct: 1,
            rule: 'Methods',
            explanations: { correct: "Incineration at ~1000°C completely destroys pathogens and medical biohazards, reducing volume to sterile ash.", wrong: { 0: "Spreads pathogens.", 2: "Highly dangerous toxic toys.", 3: "Spreads epidemics." } }
        },
        {
            id: 'q2_5',
            sentence: 'What do the "3 Rs" of waste management stand for, in order of priority?',
            options: ['Replace, Remove, Restore', 'Reduce, Reuse, Recycle', 'Recover, Rebuild, Reform', 'Reject, Retain, Return'],
            correct: 1,
            rule: 'The 3 Rs',
            explanations: { correct: "The hierarchy places Reducing waste first, Reusing items second, and Recycling materials as the last resource recovery option.", wrong: { 0: "Not standard.", 2: "Not standard.", 3: "Not standard." } }
        },
        {
            id: 'q2_6',
            sentence: 'Using an empty glass jam jar to store spices in the kitchen is an example of which "R"?',
            options: ['Reduce', 'Reuse', 'Recycle', 'Recharge'],
            correct: 1,
            rule: 'The 3 Rs',
            explanations: { correct: "Reuse involves using an item again for its original or new purpose without processing it chemically.", wrong: { 0: "Minimize buying.", 2: "Processing into new material.", 3: "Aquifer recharging." } }
        },
        {
            id: 'q2_7',
            sentence: 'What is a major environmental disadvantage of Incineration?',
            options: ['It takes up too much land', 'It releases toxic flue gases (like dioxins and furans) and heavy-metal ashes that require careful scrubbing', 'It attracts mosquitoes', 'It causes floods'],
            correct: 1,
            rule: 'Disadvantages',
            explanations: { correct: "Combusting plastics and medical materials emits toxic air pollutants, which requires highly expensive smoke scrubbers to clean.", wrong: { 0: "Requires very little land.", 2: "High heat kills all vectors.", 3: "No effect on precipitation." } }
        },
        {
            id: 'q2_8',
            sentence: 'Anaerobic digestion of animal dung and kitchen waste in a biodigester produces which clean fuel?',
            options: ['Kerosene', 'Biogas (primarily Methane)', 'LPG', 'Petrol'],
            correct: 1,
            rule: 'Biogas',
            explanations: { correct: "Anaerobic bacteria break down biological waste in the absence of oxygen to release methane (biogas), leaving a rich slurry manure.", wrong: { 0: "Fossil fuel.", 2: "Petroleum gas.", 3: "Fossil fuel." } }
        },
        {
            id: 'q2_9',
            sentence: 'What is the main difference between ordinary composting and vermicomposting?',
            options: ['Vermicomposting uses fire', 'Vermicomposting utilizes earthworms to accelerate decay and enrich the nutrient content', 'Ordinary composting is done inside houses', 'Vermicomposting only decomposes plastic'],
            correct: 1,
            rule: 'Composting',
            explanations: { correct: "Earthworms break down particles mechanically and chemically, speeding up the process from months to weeks.", wrong: { 0: "No fire involved.", 2: "Done outdoors.", 3: "Earthworms cannot eat plastic." } }
        },
        {
            id: 'q2_10',
            sentence: 'Buying items with minimal packaging or opting for e-tickets instead of paper prints represents which "R"?',
            options: ['Recycle', 'Reduce', 'Reuse', 'Restore'],
            correct: 1,
            rule: 'The 3 Rs',
            explanations: { correct: "Reduce means preventing waste generation in the first place by consuming less or choosing waste-free alternatives.", wrong: { 0: "Requires sorting and industrial process.", 2: "Using an item again.", 3: "Environmental restoration." } }
        },
        {
            id: 'q2_11',
            sentence: 'Which of the following is an ideal location for setting up a sanitary landfill?',
            options: ['In the middle of a dense residential colony', 'Outside city limits, far from water bodies and residential areas, in dry low-lying tracts', 'Directly on a riverbank', 'On top of a mountain peak'],
            correct: 1,
            rule: 'Location Factors',
            explanations: { correct: "Landfills must be away from populations to avoid odor/hazards, and away from rivers to avoid complete contamination during rain.", wrong: { 0: "Health hazard.", 2: "Water pollution.", 3: "Wind spreads waste." } }
        },
        {
            id: 'q2_12',
            sentence: 'Melting broken plastic chairs to manufacture plastic buckets is an example of _____',
            options: ['Reducing waste', 'Reusing waste', 'Recycling waste', 'Incinerating waste'],
            correct: 2,
            rule: 'The 3 Rs',
            explanations: { correct: "Recycling processes waste items into raw material to form an entirely new product.", wrong: { 0: "No chemical processing in reducing.", 1: "Reuse keeps original shape.", 3: "Incineration burns it." } }
        }
    ],

    // ──────────────────────────────────────────────────────────
    // MEGA REVISION (11 Questions)
    // ──────────────────────────────────────────────────────────
    "mega": [
        {
            id: 'mega_1',
            sentence: 'Why is composting considered a highly ecological method of organic waste disposal?',
            options: ['It releases toxic chemical smoke', 'It converts waste into valuable nutrient-rich organic manure, restoring soil health naturally', 'It destroys the soil', 'It requires massive chemicals'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "Composting models natural nutrient recycling, returning vital nitrogen, phosphorus, and organic matter to the soil.", wrong: { 0: "Zero toxic smoke.", 2: "Boosts soil fertility.", 3: "Requires no chemicals, completely biological." } }
        },
        {
            id: 'mega_2',
            sentence: 'Which of these is a "Non-biodegradable" pollutant that enters food chains and concentration increases at each trophic level?',
            options: ['Paper bag', 'DDT', 'Banana skin', 'Cotton thread'],
            correct: 1,
            rule: 'Chemical Waste',
            explanations: { correct: "DDT cannot be broken down or excreted, leading to biological magnification in higher trophic levels (e.g., birds of prey).", wrong: { 0: "Decomposes quickly.", 2: "Decomposes in weeks.", 3: "Decomposes in months." } }
        },
        {
            id: 'mega_3',
            sentence: 'Why are open landfills a primary source of Greenhouse gas emissions?',
            options: ['They release ozone', 'Anaerobic decomposition of buried organic waste generates massive amounts of Methane and Carbon Dioxide', 'They absorb all carbon', 'They burn continuously on their own'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "When organic waste is packed tightly without oxygen, anaerobic bacteria generate methane, which is 25 times more potent than CO2.", wrong: { 0: "Do not release ozone.", 2: "They are net emitters.", 3: "Rarely catch fire naturally." } }
        },
        {
            id: 'mega_4',
            sentence: 'Which "R" is highly promoted by carrying a reusable cloth shopping bag to the store?',
            options: ['Recycle', 'Reduce', 'Rot', 'Recover'],
            correct: 1,
            rule: 'The 3 Rs',
            explanations: { correct: "By using a cloth bag, you reduce the demand and generation of single-use thin plastic shopping bags.", wrong: { 0: "Cloth is not recycled in-store.", 2: "Not one of the 3 Rs.", 3: "Energy recovery." } }
        },
        {
            id: 'mega_5',
            sentence: 'What is "Leachate"?',
            options: ['A clean drinking water source', 'A highly toxic, dark liquid formed when rainwater filters through packed landfill waste, absorbing heavy chemicals', 'A type of earthworm', 'A gas released during burning'],
            correct: 1,
            rule: 'Terminology',
            explanations: { correct: "Leachate is a polluted fluid containing dissolved organic acids, heavy metals, and chemicals that accumulates at the base of landfills.", wrong: { 0: "Deadly poison.", 2: "That's red wigglers.", 3: "That's flue gas." } }
        },
        {
            id: 'mega_6',
            sentence: 'Why is the burning of dry leaves and plastic bags in open backyards highly discouraged?',
            options: ['It cools down the area', 'It releases toxic soot, carbon monoxide, and highly carcinogenic dioxins into the local air', 'It makes the air smell sweet', 'It creates too much soil'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "Low-temperature open combustion is highly incomplete, releasing dense carbon soot and deadly toxic chemical fumes.", wrong: { 0: "Releases heat.", 2: "Smells extremely foul.", 3: "Creates ash, not soil." } }
        },
        {
            id: 'mega_7',
            sentence: 'Which of the following agricultural activities causes soil and water pollution?',
            options: ['Crop rotation', 'Excessive use of chemical fertilizers and synthetic pesticides', 'Using animal manure', 'Organic farming'],
            correct: 1,
            rule: 'Sources',
            explanations: { correct: "Excess chemical inputs dissolve in rainwater, running off to poison aquatic life and depleting natural soil micro-flora.", wrong: { 0: "Eco-friendly.", 2: "Natural compost.", 3: "Highly sustainable." } }
        },
        {
            id: 'mega_8',
            sentence: 'What is the role of anaerobic decomposers in a Biogas plant?',
            options: ['They require high oxygen to burn waste', 'They ferment animal dung in the absence of oxygen to produce methane gas', 'They turn plastic into soil', 'They clean the steel pipes'],
            correct: 1,
            rule: 'Biogas',
            explanations: { correct: "Methanogenic bacteria thrive in completely oxygen-free chambers, digesting organic compounds to release combustible methane.", wrong: { 0: "Require complete absence of oxygen.", 2: "Cannot digest plastic.", 3: "Biological agents, not mechanical cleaners." } }
        },
        {
            id: 'mega_9',
            sentence: 'Which of these is a major problem of using incinerators in developing countries like India?',
            options: ['They are too cheap', 'High initial capital and running costs, and poor maintenance leading to air pollution leaks', 'They consume all water', 'They only burn wood'],
            correct: 1,
            rule: 'Problems',
            explanations: { correct: "High-temperature scrubbers and incinerator plants require immense funds and technical discipline, leading to toxic leaks if mismanaged.", wrong: { 0: "Extremely expensive.", 2: "Use fuel, not water.", 3: "Burn solid waste." } }
        },
        {
            id: 'mega_10',
            sentence: 'Segregating waste at home into "Green" and "Blue" bins helps in separating _____ respectively.',
            options: ['Dry and Wet waste', 'Wet biodegradable waste and Dry recyclable waste', 'Toxic and Radioactive waste', 'Metal and Glass waste'],
            correct: 1,
            rule: 'Terminology',
            explanations: { correct: "Green bins are strictly for wet organic kitchen scraps (biodegradable), while Blue bins are for dry scrap paper, plastic, and glass (recyclable).", wrong: { 0: "Reverse order.", 2: "Hazardous bins.", 3: "Both go in blue." } }
        },
        {
            id: 'mega_11',
            sentence: 'Why are glass bottles and aluminium cans highly prized in recycling industries?',
            options: ['They decompose on their own easily', 'They can be melted down and recycled infinitely without any loss in material quality, saving immense energy', 'They are made of wood', 'They do not melt at all'],
            correct: 1,
            rule: 'Give Reason',
            explanations: { correct: "Recycling glass and metals consumes up to 95% less energy than extracting and refining virgin sand and bauxite ore.", wrong: { 0: "Non-biodegradable.", 2: "Mineral-based.", 3: "Melt at high heat." } }
        }
    ]
};
