window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 50, subject: "biology",    name: "Cell Cycle & Cell Division",        difficulty: "Moderate",  length: "Normal",  tags: ["14 SLIDES", "70 QUESTIONS"], href: "subjects/biology/cell_division.html", desc: "Interphase, mitosis (PMAT), meiosis, significance, comparison of plant & animal cell division, and chromosome structure." },
    { num: 51, subject: "biology",    name: "Genetics",                          difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Mendel's Laws, monohybrid & dihybrid crosses, sex determination, sex-linked inheritance, and genetic disorders." },
    { num: 52, subject: "biology",    name: "Absorption by Roots",               difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Osmosis, diffusion, imbibition, active/passive transport, turgidity, flaccidity, plasmolysis, and root pressure." },
    { num: 53, subject: "biology",    name: "Transpiration",                     difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Process, significance, factors affecting transpiration rate, stomatal mechanism, and ganong's potometer experiments." },
    { num: 54, subject: "biology",    name: "Photosynthesis",                    difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Light & dark reactions, chemical equation, factors affecting rate, importance, and experimental demonstrations." },
    { num: 55, subject: "biology",    name: "Chemical Coordination in Plants",   difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Auxins, gibberellins, cytokinins — role in growth. Tropic movements: phototropism, geotropism, hydrotropism." },
    { num: 56, subject: "biology",    name: "Circulatory System",                difficulty: "Moderate",  length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Blood composition, heart structure & working, double circulation, blood vessels, lymph, and blood groups." },
    { num: 57, subject: "biology",    name: "Excretory System",                  difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Structure of kidney & nephron, urine formation (ultrafiltration, reabsorption, secretion), and dialysis." },
    { num: 58, subject: "biology",    name: "Nervous System",                    difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Neuron structure, CNS/PNS/ANS, brain structure & functions, spinal cord, reflex arc, and reflex action." },
    { num: 59, subject: "biology",    name: "Endocrine System",                  difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Endocrine vs exocrine glands. Pituitary, thyroid, adrenal, pancreas — hormones, functions & disorders." },
    { num: 60, subject: "biology",    name: "Reproductive System",               difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Male & female organs, fertilisation, implantation, placenta, menstrual cycle, and puberty changes." },
    { num: 61, subject: "biology",    name: "Population & Pollution",            difficulty: "Easy",      length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Population explosion, causes & control. Air, water, soil, noise pollution — sources, effects & abatement. Human evolution basics." }
);
