window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 1, subject: "chemistry",  name: "Periodic Table & Periodicity",      difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Periodic properties (atomic size, ionization potential, electron affinity, electronegativity) and their variation in groups & periods." },
    { num: 2, subject: "chemistry",  name: "Chemical Bonding",                  difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Electrovalent (ionic), covalent & coordinate bonding. Electron dot structures, properties of ionic vs covalent compounds." },
    { num: 3, subject: "chemistry",  name: "Acids, Bases & Salts",              difficulty: "Easy",      length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Definitions, pH scale, indicators, types of salts (normal, acid, basic), and neutralization reactions." },
    { num: 4, subject: "chemistry",  name: "Analytical Chemistry",              difficulty: "Easy",      length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Action of NaOH & NH₄OH on salt solutions of Fe, Cu, Zn, Pb — identification of cations by colour of precipitate." },
    { num: 5, subject: "chemistry",  name: "Mole Concept & Stoichiometry",      difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Gay-Lussac's Law, Avogadro's Law, molar volume, mole calculations, and balanced equation-based numericals." },
    { num: 6, subject: "chemistry",  name: "Electrolysis",                      difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Electrolytes & non-electrolytes, mechanism of electrolysis, selective discharge, electroplating, and applications." },
    { num: 7, subject: "chemistry",  name: "Metallurgy",                        difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Occurrence of metals, ores vs minerals, extraction stages (concentration, reduction, refining), and aluminium extraction." },
    { num: 8, subject: "chemistry",  name: "Study of Compounds (HCl, NH₃, HNO₃, H₂SO₄)", difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Lab preparation, industrial processes (Haber, Ostwald, Contact), properties, tests, and chemical reactions." },
    { num: 9, subject: "chemistry",  name: "Organic Chemistry",                 difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Unique nature of carbon, homologous series, isomerism, IUPAC nomenclature, hydrocarbons, alcohols & carboxylic acids." }
);
