window.ICSE_CHAPTERS = window.ICSE_CHAPTERS || [];
window.ICSE_CHAPTERS.push(
    { num: 1,  subject: "eng-lang",   name: "Articles",                          difficulty: "Easy",      length: "Short",   tags: ["16 SLIDES", "7 EXERCISES", "100 QUESTIONS"], href: "articles.html", desc: "Master the usage of A, An, and The. Covers indefinite/definite articles, sound exceptions, omissions, and all textbook exercises." },
    { num: 2,  subject: "eng-lang",   name: "Subject-Verb Agreement",            difficulty: "Moderate",  length: "Normal",  tags: ["16 SLIDES", "7 EXERCISES", "100 QUESTIONS"], href: "sva.html", desc: "Learn all 15 rules of concord — singular/plural subjects, collective nouns, either/or, indefinite pronouns, and tricky exceptions. Dropdown-based quizzes with detailed explanations." },
    { num: 3,  subject: "eng-lang",   name: "Tenses",                            difficulty: "Moderate",  length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "All 12 tense forms — Simple, Continuous, Perfect & Perfect Continuous across Past, Present, and Future. Sequence of tenses & common errors." },
    { num: 4,  subject: "eng-lang",   name: "Prepositions",                      difficulty: "Easy",      length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Time, place, movement & fixed prepositions. Verb-preposition combinations, common confusions (in/into, on/upon, between/among)." },
    { num: 5,  subject: "eng-lang",   name: "Active & Passive Voice",            difficulty: "Moderate",  length: "Normal",  tags: ["COMING SOON"], href: "#", desc: "Transformation rules for all tenses, modals, imperatives, and interrogative sentences. Board-style \"Do as Directed\" practice." },
    { num: 6,  subject: "eng-lang",   name: "Direct & Indirect Speech",          difficulty: "Moderate",  length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Reported speech rules — statements, questions, commands, requests, exclamations. Tense shifts, pronoun changes & time expression updates." },
    { num: 7,  subject: "eng-lang",   name: "Sentence Transformation",           difficulty: "Difficult", length: "Lengthy", tags: ["COMING SOON"], href: "#", desc: "Simple↔Compound↔Complex, affirmative/negative interchange, degree conversions, exclamatory/assertive & sentence synthesis." },
    { num: 8,  subject: "eng-lang",   name: "Conditional Sentences",             difficulty: "Moderate",  length: "Short",   tags: ["COMING SOON"], href: "#", desc: "Zero, First, Second & Third conditionals. \"If\" clause patterns, mixed conditionals, and \"unless/provided that\" variations." }
);
